### default Profile ###
spring:
  profiles:
    active: local
    include:
      - oauth
      - session
      - aws

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

#  datasource:
#    url: jdbc:h2:mem:practical-test
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: anchor-image-stroage
    region:
      static: ap-northeast-2
    stack:
      auto: false